#! /usr/bin/perl -w
use strict;
use mClient;

my $memo;

sub IFSq_msg {
  my $type = shift;
  $type = 2 unless $type =~ m/^\d$/;
  my $msg = join '', @_;
  unless ( defined($memo) ) {
    $memo = mClient::connect("memo");
  }
  my $hdr = '';
  if ($type == 1) {
    $hdr = "[WARNING] ";
  } elsif ($type == 2) {
    $hdr = "[ERROR] ";
  } elsif ($type == 3) {
    $hdr = "[FATAL] ";
  } elsif ($type > 3) {
    $hdr = "[INTERNAL] ";
  }
  my @gmt = gmtime;
  my $time = sprintf("IFS: %02d:%02d:%02d", $gmt[2], $gmt[1], $gmt[0]);
  my $buf = "$time $hdr$msg\n";
  $memo->print($buf);
  exit(1) if $type > 2;
}

IFSq_msg(0, "This is a test");
