#! /bin/sh
# bin2csv $dir

function nl_error {
  echo bin2csv: ERROR: $* >&2
  exit 1
}

Extractions="infoext IFSengext"

dir=$1
[ -d $dir ] || nl_error "Cannot locate directory '$dir'"
[ -f $dir/VERSION ] || nl_error "Cannot locate VERSION in '$dir'"
ver=$(cat $dir/VERSION)
dir=$(realpath $dir)
RUN=$(basename $dir)
dest=$dir/TM
[ -d $dest ] || mkdir $dest || nl_error "Cannot mkdir '$dest'"

cd /home/citco2
extract $dir $Extractions
cd /home/citco2/anal/$RUN

cp cceng_1.csv $dest/${RUN}_1.csv

rm -f *.csv
