#! /bin/bash
# bin2csv $dir

function nl_error {
  echo bin2csv: ERROR: $* >&2
  exit 1
}

Extractions=IFSengext

dir=$1
[ -d $dir ] || nl_error "Cannot locate directory '$dir'"
[ -f $dir/VERSION ] || nl_error "Cannot locate VERSION in '$dir'"
ver=$(cat $dir/VERSION)
dir=$(realpath $dir)
RUN=$(basename $dir)
dest=$dir/TM
[ -d $dest ] || mkdir $dest
[ -d $dest ] || nl_error "Cannot mkdir '$dest'"

cd /home/citco2
# Hack until we retire runs before VERSION 3.0.9
[ -d $dir/scan ] && Extractions="$Extractions infoext"
extract $dir $Extractions
cd /home/citco2/anal/$RUN

cp -v cceng_1.csv $dest/${RUN}_1.csv

# Leave the csv in anal for short term retrieval of engineering data
# rm -f *.csv
