#!/bin/sh

tmpdir="/home/citco2/transfer"
TXSCRIPT="$tmpdir/transfer-request.sh"

NOW=$(date +_%F_%T)

NEWSCRIPT=$TXSCRIPT$NOW

if [ -f "$TXSCRIPT" ]; then
  mv "$TXSCRIPT" "$NEWSCRIPT"
  $NEWSCRIPT
fi

