function pccestale(varargin);
% pccestale( [...] );
% Enclosure Stale
h = timeplot({'STEnc_stale'}, ...
      'Enclosure Stale', ...
      'Stale', ...
      {'STEnc\_stale'}, ...
      varargin{:} );
