function pccifshkt(varargin)
% pccifshkt( [...] );
% IFS HK Temps
h = timeplot({'ScBlkT','IFSSrcT'}, ...
      'IFS HK Temps', ...
      'Temps', ...
      {'ScBlkT','IFSSrcT'}, ...
      varargin{:} );
