function pccifshks(varargin)
% pccifshks( [...] );
% IFS HK Status
h = ne_dstat({
  'DiagScanS', 'IFSDiag', 0; ...
	'DiagDetS', 'IFSDiag', 1; ...
	'DiagHeNeS', 'IFSDiag', 2; ...
	'DiagIRSrcS', 'IFSDiag', 3; ...
	'DiagAUS', 'IFSDiag', 4; ...
	'DiagRdyS', 'IFSDiag', 5 }, 'Status', varargin{:} );
