function pccifsl(varargin)
% pccifsl( [...] );
% IFS Laser
h = timeplot({'LasAAF','LasAOF','LasBAF','LasBOF'}, ...
      'IFS Laser', ...
      'Laser', ...
      {'LasAAF','LasAOF','LasBAF','LasBOF'}, ...
      varargin{:} );
