function pcclns(varargin)
% pcclns( [...] );
% LN2 Status
h = ne_dstat({
  'LN2Pump', 'LN2Stat', 1; ...
	'LN2Valve', 'LN2Stat', 2; ...
	'LN2TMB', 'LN2Stat', 3; ...
	'LN2Alarm', 'LN2Stat', 7; ...
	'LN2Init', 'LN2DrvStat', 0 }, 'Status', varargin{:} );
