function pcclnas(varargin)
% pcclnas( [...] );
% LN2 A Stat
h = ne_dstat({
  'LN2Alarm', 'LN2Stat', 7; ...
	'LN2_VES_AL', 'LN2AlarmStat', 1; ...
	'LN2_TMB_AL', 'LN2AlarmStat', 2; ...
	'LN2_EXS_AL', 'LN2AlarmStat', 3; ...
	'LN2_MNS_AL', 'LN2AlarmStat', 4; ...
	'LN2_BLK_AL', 'LN2AlarmStat', 5; ...
	'LN2_HOT_AL', 'LN2AlarmStat', 8; ...
	'LN2_FRZ_AL', 'LN2AlarmStat', 9; ...
	'LN2_NOP_AL', 'LN2AlarmStat', 10 }, 'A Stat', varargin{:} );
