function pccps(varargin)
% pccps( [...] );
% Power Status
h = ne_dstat({
  'WP_Pump_S', 'webpower_status', 0; ...
	'WP_PDISO8_S', 'webpower_status', 1; ...
	'WP_MKS925_S', 'webpower_status', 2; ...
	'WP_AXIS_P1378_S', 'webpower_status', 3 }, 'Status', varargin{:} );
