function pccstr(varargin)
% pccstr( [...] );
% ST Radiance
h = timeplot({'model_intensity','WTX_SolRad'}, ...
      'ST Radiance', ...
      'Radiance', ...
      {'Model','Observed'}, ...
      varargin{:} );
