function pccstd(varargin)
% pccstd( [...] );
% ST Diff
h = timeplot({'ST_azi_diff','ST_ele_diff'}, ...
      'ST Diff', ...
      'Diff', ...
      {'ST\_azi\_diff','ST\_ele\_diff'}, ...
      varargin{:} );
