function pccwtx_precipt(varargin)
% pccwtx_precipt( [...] );
% WTX Precip Type
h = timeplot({'WTX_PrecipType'}, ...
      'WTX Precip Type', ...
      'Type', ...
      {'WTX\_PrecipType'}, ...
      varargin{:} );
