function pccwtxws(varargin)
% pccwtxws( [...] );
% WTX Wind Speed
h = timeplot({'WTX_WindSpd','wslimit_fast','wslimit_slow'}, ...
      'WTX Wind Speed', ...
      'Speed', ...
      {'WTX\_WindSpd','fast','slow'}, ...
      varargin{:} );
