function pccwtxsf(varargin)
% pccwtxsf( [...] );
% WTX Status Fresh
h = ne_dstat({
  'RH', 'WTX_Fresh', 0; ...
	'WD', 'WTX_Fresh', 1; ...
	'PTWQSR', 'WTX_Fresh', 2; ...
	'AT', 'WTX_Fresh', 3; ...
	'DP', 'WTX_Fresh', 4; ...
	'WSPC', 'WTX_Fresh', 5; ...
	'AP', 'WTX_Fresh', 6 }, 'Fresh', varargin{:} );
