function pccwtxrh(varargin);
% pccwtxrh( [...] );
% WTX RH
h = timeplot({'RH_Open_Pct','RH_Close_Pct','WTX_RH'}, ...
      'WTX RH', ...
      'RH', ...
      {'RH\_Open\_Pct','RH\_Close\_Pct','WTX\_RH'}, ...
      varargin{:} );
