function pccwtxt(varargin)
% pccwtxt( [...] );
% WTX Temp
h = timeplot({'WTX_AirT','WTX_DewPt'}, ...
      'WTX Temp', ...
      'Temp', ...
      {'WTX\_AirT','WTX\_DewPt'}, ...
      varargin{:} );
