function pccwtxss(varargin);
% pccwtxss( [...] );
% WTX Status Stale
h = timeplot({'WTX_dev_stale','WTX_drv_stale'}, ...
      'WTX Status Stale', ...
      'Stale', ...
      {'Dev','Drv'}, ...
      varargin{:} );
