function pccwtx_precipi(varargin)
% pccwtx_precipi( [...] );
% WTX Precip Intensity
h = timeplot({'WTX_PrecipInt'}, ...
      'WTX Precip Intensity', ...
      'Intensity', ...
      {'WTX\_PrecipInt'}, ...
      varargin{:} );
